name: digital_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  flare_flutter: ^1.7.3
  provider: ^3.2.0
  simple_animations: ^1.3.4
  mdi: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Comfortaa
      fonts:
       - asset: third_party/Comfortaa-Regular.ttf
  assets:
    - assets/
    - assets/mountains/
